changelog
Finastra/fds-angular pull request #43
Opened 2023-05-08 14:00 UTC by BeataKr

2023-05-16 12:50 UTC, BeataKr commented
@rbordeanu should can you please have a look? not sure about text position to "new" span and border around

I don't know how to handle the solution with flex-layout - any tip for that? :)

2023-05-16 13:20 UTC, rbordeanu commented
I'm wondering why you have formatting errors?
It should auto format on save, can you check .vscode settings for that?

Alternatively, just run `nx format:write` before committing.

2023-05-16 13:32 UTC, achilehero commented
> I'm wondering why you have formatting errors? It should auto format on save, can you check .vscode settings for that?
> 
> Alternatively, just run `nx format:write` before committing.

https://github.com/Finastra/fds-angular/blob/main/.vscode/settings.json - it's not formatting automatically on save.

2023-05-16 13:40 UTC, rbordeanu requested changes

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
> +        background-image: linear-gradient(to right, #694ED6, #C137A2);
```suggestion
        background-image: linear-gradient(to right, var(--fds-primary), var(--fds-secondary));
```

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
> +      @include color.property(border-color, outline);
```suggestion
      border-bottom: 1px solid var(--fds-outline);
```

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
> +      @include color.property(border-color, outline);
The idea is to include the property mixin only when it's more convenient.
In cases like this one (and others below), it's more concise to use css vars directly.

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
> +        @include color.property(border, primary);
```suggestion
        border: 8px solid var(--fds-primary);
```

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
>      // @include flex-layout.layout-bp(xs) {
```suggestion
    @include breakpoints.flex-breakpoint('xs') {
    
```

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
>      // @include flex-layout.layout-bp(xs) {
Check https://github.com/Finastra/fds-angular/blob/main/libs/angular-components/toaster/src/toaster.component.scss#L42 for an example.

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/changelog.component.scss
> -@use '@finastra/angular-theme' as fds;
You can keep this, and all the $uxg-spacing- variables referenced in this file.

2023-05-16 13:40 UTC, rbordeanu commented on libs/angular-components/changelog/src/_changelog.theme.scss
> +          @include color.background(#E5E5E5);
See here an example on how to get a color with opacity from an existing token, using a new mixin:
https://github.com/Finastra/fds-angular/blob/main/libs/angular-theme/lib/toolbar/_toolbar-theme.scss#L16

2023-05-17 06:44 UTC, BeataKr commented
> I'm wondering why you have formatting errors? It should auto format on save, can you check .vscode settings for that?
> 
> Alternatively, just run `nx format:write` before committing.

due to lack of `lack of `"editor.formatOnSave": true,` ` in settings?

2023-05-17 13:41 UTC, BeataKr commented
still I need to fix date position

2023-05-17 17:27 UTC, rbordeanu requested changes

2023-05-18 06:28 UTC, BeataKr commented on libs/angular-components/changelog/src/changelog.component.scss
> +    margin-bottom: 8px;
true :D will revert

2023-05-19 13:41 UTC, BeataKr commented
agr how to move `version` and `version-id` to the left side of bullet? 😄

2023-06-05 07:50 UTC, Ping-YUAN approved these changes

2023-06-05 07:51 UTC, merged