status stepper
Finastra/fds-angular pull request #52
Opened 2023-05-18 12:02 UTC by BeataKr

2023-05-18 12:53 UTC, rbordeanu requested changes

2023-05-18 12:53 UTC, rbordeanu commented on apps/angular-test-app/src/styles.scss
> +  @include status-stepper.theme($theme);
only need this one, it includes the other two themes

2023-05-18 12:53 UTC, rbordeanu commented on libs/angular-components/status-steps/_horizontal-status-stepper.theme.scss
> +        color: rgba(var(primary), 0.5);
not sure this is valid?

2023-05-18 12:53 UTC, rbordeanu commented on libs/angular-components/status-steps/_horizontal-status-stepper.theme.scss
> +@use '@finastra/fds-theme/color' as color;
not used?

2023-05-18 12:53 UTC, rbordeanu commented on libs/angular-components/status-steps/_uxg-status-step.theme.scss
> +@use '@finastra/fds-theme/color' as color;
not used?

(not needed for css vars, only if you use mixins)

2023-05-18 12:53 UTC, rbordeanu commented on libs/angular-components/status-steps/_status-stepper.theme.scss
> +@use 'uxg-status-step.theme' as uxg-status-step;
'xxx' as 'yyy' syntax not required, unless you want to rename it, otherwise the name will be whatever it is before the .theme

2023-05-18 13:30 UTC, BeataKr commented
wanted to be close to `Horizontal stepper label bottom` https://design.fusionfabric.cloud/components/stepper, so used typography on uxg-status-step

2023-05-22 08:23 UTC, achilehero commented on apps/angular-test-app/src/styles.scss
> +@use 'angular-components/status-steps/uxg-status-step.theme' as uxg-status-step;
So you can remove this line, right? Since you used the rename as `status-stepper`

2023-05-22 09:21 UTC, rbordeanu approved these changes

2023-05-22 09:24 UTC, achilehero approved these changes

2023-05-22 09:24 UTC, merged