Feature/angular update 16 17
Finastra/fds-angular pull request #76
Opened 2024-06-04 13:50 UTC by sdklgjdklfjg

2024-06-14 07:56 UTC, sunil237216 commented on libs/angular-components/avatar/src/avatar.component.ts
> +  md5 = new Md5();
Can't we inject this in constructor?

2024-06-14 08:09 UTC, sunil237216 commented on tools/devkit/package.json
> +    "globby": "11.0.4",
why have we added this library?

2024-06-14 09:15 UTC, sdklgjdklfjg commented on libs/angular-components/avatar/src/avatar.component.ts
> +  md5 = new Md5();
This library is simply not providing static method anymore (Md5.hashStr) and I believe it's documentation example. Injecting external constructors likely won't work? Dunno, I haven't tried really... I mean - propper way would be to create service for this lib, wrap it into function to satisfy adapter pattern etc. but it's just this one use so it feels like overkill. Also I tried to search browser api for similar functionality but I couldn't find any resonable replacement.

2024-06-14 09:17 UTC, sdklgjdklfjg commented on tools/devkit/package.json
> +    "globby": "11.0.4",
It's in parent package with higher version, but it seems like it will work without downgrading, I'll check that thanks!

2024-06-18 09:23 UTC, BeataKr requested changes

2024-06-18 09:23 UTC, BeataKr commented on apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.html
> +              <span>&#123;&#123;</span>row <span>&#125;&#125; &#123;&#123;</span>subtitle <span>&#125;&#125;</span>
can we resolve each _&#no_ by any charset?

2024-06-18 09:23 UTC, BeataKr commented on libs/angular-components/package.json
> +    "@angular/core": "^17.3.9",
think we wanted to get of rid from ^ in versions

2024-06-18 09:23 UTC, BeataKr commented on libs/angular-theme/package.json
> +    "@angular/material": "^17.3.9"
can we avoid ^?

2024-06-18 09:23 UTC, BeataKr commented on package.json
> +    "build:theme": "nx build angular-theme --prod && cd libs/angular-theme/prebuilt-theme && npm pack",
maybe we can add separate script for packing, because there is no need to pack anything after build

2024-06-18 09:23 UTC, BeataKr commented on package.json
> +    "@actions/core": "^1.10.1",
^

2024-06-18 12:26 UTC, jwarzocha reviewed
![msedge_EnicV6bFmC](https://github.com/Finastra/fds-angular/assets/2733238/fdc0609e-7ceb-4786-b29b-8f516c79f993)

2024-06-18 13:16 UTC, sdklgjdklfjg commented on .gitignore
> +.vscode
added this couse my git manager is showing .vscode dir, didn't work so I'll remove it

2024-07-08 17:45 UTC, allenkepler-finastra approved these changes

2024-07-09 09:24 UTC, sdklgjdklfjg commented on libs/angular-theme/package.json
> +    "@angular/material": "^17.3.9"
with ^ we can npm install without --legacy-peer-deps, so I'll leave it like that

2024-07-09 09:25 UTC, sdklgjdklfjg commented on package.json
> +    "@actions/core": "^1.10.1",
without carets npm install fail, with ^ we can npm install without --legacy-peer-deps, so I vote for leaving them

2024-07-09 09:25 UTC, sdklgjdklfjg commented on libs/angular-components/package.json
> +    "@angular/core": "^17.3.9",
without carets npm install fail, with ^ we can npm install without --legacy-peer-deps, so I vote for leaving them

2024-07-09 09:33 UTC, sdklgjdklfjg commented on apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.html
> +              <span>&#123;&#123;</span>row <span>&#125;&#125; &#123;&#123;</span>subtitle <span>&#125;&#125;</span>
separate issue created

2024-07-09 13:57 UTC, sdklgjdklfjg commented on package.json
> +    "build:theme": "nx build angular-theme --prod && cd libs/angular-theme/prebuilt-theme && npm pack",
done

2024-07-09 14:14 UTC, dagmaradolasinska approved these changes

2024-07-09 14:29 UTC, merged